version: '3.8'

services:
  students_courses_service:
    build: .
    container_name: students_courses_service
    ports:
      - "3002:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=students_courses_db
      - DB_PORT=5432
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - db
      - rabbitmq
    restart: always
    networks:
      - app-network

  db:
    image: postgres:14-alpine
    container_name: students_courses_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: students_courses_db
    ports:
      - "5434:5432"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - students_courses_db_data:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: students_courses_rabbitmq
    ports:
      - "5674:5672"   # AMQP port
      - "15674:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    networks:
      - app-network

volumes:
  students_courses_db_data:
  rabbitmq_data:

networks:
  app-network:
    driver: bridge