version: '3.8'

services:
  app:
    build: .
    ports:
      - "3007:3000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=user_management_db
      - DB_PORT=5432
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_EXPIRATION=24h
    volumes:
      - ./src:/app/src
    restart: unless-stopped

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=user_management_db
    ports:
      - "5437:5432"
    volumes:
      - user_management_data:/var/lib/postgresql/data
      - ./src/database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
  user_management_data: